import { makeStyles, tokens } from "@fluentui/react-components";

export const useProfileStyles = makeStyles({
  content: { padding: "16px", maxWidth: "720px", margin: "0 auto" },
  tabs: {
    display: "grid",
    gridTemplateColumns: "repeat(4, minmax(0, 1fr))",
    gap: "4px",
    padding: "4px",
    marginBottom: "16px",
    borderRadius: "10px",
    backgroundColor: "#e6ece9",
  },
  tab: {
    border: 0,
    borderRadius: "7px",
    padding: "9px 4px",
    color: "#496059",
    background: "transparent",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  activeTab: { color: "#17493c", backgroundColor: "white", boxShadow: "0 1px 3px rgba(0,0,0,.08)" },
  stack: { display: "flex", flexDirection: "column", gap: "12px" },
  card: { padding: "16px", borderRadius: "12px", boxShadow: "0 2px 8px rgba(18,56,47,.06)" },
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "12px",
  },
  sectionTitle: { margin: 0, fontSize: "16px", fontWeight: 650 },
  muted: {
    margin: "4px 0 0",
    color: tokens.colorNeutralForeground3,
    fontSize: "12px",
    lineHeight: 1.45,
  },
  stats: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "8px" },
  stat: {
    padding: "12px 8px",
    textAlign: "center",
    backgroundColor: "#edf4f1",
    borderRadius: "10px",
  },
  statButton: {
    border: 0,
    padding: "12px 8px",
    textAlign: "center",
    backgroundColor: "#edf4f1",
    borderRadius: "10px",
    cursor: "pointer",
    ":hover": { backgroundColor: "#dcebe5" },
  },
  statNumber: { display: "block", color: "#17493c", fontSize: "22px", fontWeight: 700 },
  statLabel: {
    color: "#60736d",
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: ".5px",
  },
  chips: { display: "flex", flexWrap: "wrap", gap: "7px", marginTop: "12px" },
  chip: {
    border: "1px solid #c9d7d2",
    borderRadius: "999px",
    padding: "7px 10px",
    color: "#3e554e",
    backgroundColor: "white",
    fontSize: "12px",
    cursor: "pointer",
  },
  selectedChip: {
    border: "1px solid #2b715e",
    color: "#17493c",
    backgroundColor: "#dcefe9",
    fontWeight: 600,
  },
  formGrid: { display: "grid", gap: "12px", marginTop: "14px" },
  quickAdd: { position: "relative", marginTop: "14px" },
  quickAddControls: { display: "flex", gap: "8px" },
  quickAddInput: { flexGrow: 1 },
  inputHint: {
    margin: "6px 0 0",
    color: tokens.colorNeutralForeground3,
    fontSize: "11px",
  },
  searchResults: {
    position: "absolute",
    zIndex: 10,
    top: "38px",
    right: "40px",
    left: 0,
    overflow: "hidden",
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: "8px",
    backgroundColor: "white",
    boxShadow: "0 8px 24px rgba(18,56,47,.16)",
  },
  searchResult: {
    display: "flex",
    width: "100%",
    flexDirection: "column",
    gap: "2px",
    border: 0,
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: "9px 11px",
    textAlign: "left",
    color: tokens.colorNeutralForeground1,
    backgroundColor: "white",
    cursor: "pointer",
    ":hover": { backgroundColor: "#edf4f1" },
  },
  searchResultName: { fontSize: "12px", fontWeight: 650 },
  searchResultMeta: { color: tokens.colorNeutralForeground3, fontSize: "10px" },
  formActions: { display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "4px" },
  select: {
    width: "100%",
    minHeight: "32px",
    boxSizing: "border-box",
    border: "1px solid #c7c7c7",
    borderRadius: "4px",
    padding: "5px 8px",
    color: "#242424",
    backgroundColor: "white",
    font: "inherit",
  },
  companyRow: { display: "flex", alignItems: "flex-start", gap: "10px" },
  companyIcon: {
    display: "grid",
    placeItems: "center",
    width: "34px",
    height: "34px",
    flexShrink: 0,
    borderRadius: "9px",
    color: "#1f5d4d",
    backgroundColor: "#dcefe9",
  },
  companyBody: { minWidth: 0, flexGrow: 1 },
  companyName: { margin: 0, fontSize: "14px", fontWeight: 650 },
  companyMeta: { margin: "3px 0 0", color: tokens.colorNeutralForeground3, fontSize: "11px" },
  notes: {
    margin: "8px 0 0",
    color: tokens.colorNeutralForeground2,
    fontSize: "12px",
    lineHeight: 1.45,
  },
  companyLinks: {
    display: "flex",
    gap: "10px",
    marginTop: "7px",
    fontSize: "11px",
    "& a": { color: "#1f5d4d", fontWeight: 600, textDecoration: "none" },
    "& a:hover": { textDecoration: "underline" },
  },
  enrichmentStatus: { justifyContent: "flex-start", marginTop: "8px", fontSize: "11px" },
  enrichmentFailure: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "8px",
    marginTop: "8px",
    color: tokens.colorPaletteRedForeground1,
    fontSize: "11px",
  },
  empty: { padding: "28px 18px", textAlign: "center", color: tokens.colorNeutralForeground3 },
  callout: {
    padding: "14px",
    borderLeft: "3px solid #2b715e",
    backgroundColor: "#edf4f1",
    borderRadius: "8px",
  },
  calloutText: { margin: 0, fontSize: "12px", lineHeight: 1.5 },
  inlineActions: { display: "flex", gap: "2px" },
  intro: {
    padding: "2px 2px 4px",
    "& h2": { margin: 0, color: "#17493c", fontSize: "18px" },
    "& p": { margin: "5px 0 0", color: tokens.colorNeutralForeground3, fontSize: "12px" },
  },
  addRow: { display: "grid", gridTemplateColumns: "1fr auto", gap: "8px", marginTop: "14px" },
  editableChips: { display: "flex", flexWrap: "wrap", gap: "7px", marginTop: "12px" },
  editableChip: {
    display: "inline-flex",
    alignItems: "center",
    gap: "5px",
    border: "1px solid #bfd4cc",
    borderRadius: "999px",
    padding: "5px 6px 5px 10px",
    color: "#17493c",
    backgroundColor: "#edf7f3",
    fontSize: "12px",
    "& button": {
      display: "grid",
      placeItems: "center",
      border: 0,
      padding: "2px",
      color: "#496059",
      background: "transparent",
      cursor: "pointer",
    },
  },
  attentionList: { display: "flex", flexDirection: "column", margin: "12px 0 8px" },
  attentionRow: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    borderBottom: "1px solid #e8ecea",
    padding: "10px 0",
  },
  rank: {
    display: "grid",
    placeItems: "center",
    width: "25px",
    height: "25px",
    borderRadius: "50%",
    color: "white",
    backgroundColor: "#17493c",
    fontSize: "11px",
    fontWeight: 700,
  },
  emptyText: { margin: "12px 0", color: tokens.colorNeutralForeground3, fontSize: "12px" },
  eventList: { display: "flex", flexDirection: "column", gap: "2px", marginTop: "10px" },
  eventRow: {
    display: "grid",
    gridTemplateColumns: "10px 1fr",
    gap: "8px",
    alignItems: "start",
    padding: "9px 0",
    borderBottom: "1px solid #edf0ef",
    "& strong": { fontSize: "12px" },
    "& p": { margin: "2px 0", color: tokens.colorNeutralForeground2, fontSize: "12px" },
    "& small": { color: tokens.colorNeutralForeground3, fontSize: "10px" },
  },
  impactDot: { width: "8px", height: "8px", marginTop: "5px", borderRadius: "50%" },
  positive: { backgroundColor: "#2b8a66" },
  negative: { backgroundColor: "#c13d3d" },
  neutral: { backgroundColor: "#85918d" },
  companyActions: { display: "flex", flexDirection: "column", gap: "10px" },
  eventForm: {
    display: "grid",
    gap: "10px",
    borderTop: "1px solid #e5e9e7",
    marginTop: "12px",
    paddingTop: "12px",
  },
  twoColumns: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px" },
});
