import { makeStyles, tokens } from "@fluentui/react-components";

export const useProfileStyles = makeStyles({
  content: { padding: "16px", maxWidth: "720px", margin: "0 auto" },
  tabs: {
    display: "grid",
    gridTemplateColumns: "repeat(3, 1fr)",
    gap: "4px",
    padding: "4px",
    marginBottom: "16px",
    borderRadius: "10px",
    backgroundColor: "#e6ece9",
  },
  tab: {
    border: 0,
    borderRadius: "7px",
    padding: "9px 4px",
    color: "#496059",
    background: "transparent",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  activeTab: { color: "#17493c", backgroundColor: "white", boxShadow: "0 1px 3px rgba(0,0,0,.08)" },
  stack: { display: "flex", flexDirection: "column", gap: "12px" },
  card: { padding: "16px", borderRadius: "12px", boxShadow: "0 2px 8px rgba(18,56,47,.06)" },
  cardHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: "12px",
  },
  sectionTitle: { margin: 0, fontSize: "16px", fontWeight: 650 },
  muted: {
    margin: "4px 0 0",
    color: tokens.colorNeutralForeground3,
    fontSize: "12px",
    lineHeight: 1.45,
  },
  stats: { display: "grid", gridTemplateColumns: "repeat(3, 1fr)", gap: "8px" },
  stat: {
    padding: "12px 8px",
    textAlign: "center",
    backgroundColor: "#edf4f1",
    borderRadius: "10px",
  },
  statNumber: { display: "block", color: "#17493c", fontSize: "22px", fontWeight: 700 },
  statLabel: {
    color: "#60736d",
    fontSize: "10px",
    textTransform: "uppercase",
    letterSpacing: ".5px",
  },
  chips: { display: "flex", flexWrap: "wrap", gap: "7px", marginTop: "12px" },
  chip: {
    border: "1px solid #c9d7d2",
    borderRadius: "999px",
    padding: "7px 10px",
    color: "#3e554e",
    backgroundColor: "white",
    fontSize: "12px",
    cursor: "pointer",
  },
  selectedChip: {
    border: "1px solid #2b715e",
    color: "#17493c",
    backgroundColor: "#dcefe9",
    fontWeight: 600,
  },
  formGrid: { display: "grid", gap: "12px", marginTop: "14px" },
  formActions: { display: "flex", justifyContent: "flex-end", gap: "8px", marginTop: "4px" },
  select: {
    width: "100%",
    minHeight: "32px",
    boxSizing: "border-box",
    border: "1px solid #c7c7c7",
    borderRadius: "4px",
    padding: "5px 8px",
    color: "#242424",
    backgroundColor: "white",
    font: "inherit",
  },
  companyRow: { display: "flex", alignItems: "flex-start", gap: "10px" },
  companyIcon: {
    display: "grid",
    placeItems: "center",
    width: "34px",
    height: "34px",
    flexShrink: 0,
    borderRadius: "9px",
    color: "#1f5d4d",
    backgroundColor: "#dcefe9",
  },
  companyBody: { minWidth: 0, flexGrow: 1 },
  companyName: { margin: 0, fontSize: "14px", fontWeight: 650 },
  companyMeta: { margin: "3px 0 0", color: tokens.colorNeutralForeground3, fontSize: "11px" },
  notes: {
    margin: "8px 0 0",
    color: tokens.colorNeutralForeground2,
    fontSize: "12px",
    lineHeight: 1.45,
  },
  empty: { padding: "28px 18px", textAlign: "center", color: tokens.colorNeutralForeground3 },
  callout: {
    padding: "14px",
    borderLeft: "3px solid #2b715e",
    backgroundColor: "#edf4f1",
    borderRadius: "8px",
  },
  calloutText: { margin: 0, fontSize: "12px", lineHeight: 1.5 },
  inlineActions: { display: "flex", gap: "2px" },
});
