import { makeStyles, tokens } from "@fluentui/react-components";

export const useChatStyles = makeStyles({
  root: {
    display: "grid",
    gridTemplateRows: "auto minmax(280px, 1fr) auto",
    minHeight: "520px",
    overflow: "hidden",
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "12px",
    backgroundColor: "white",
    boxShadow: "0 2px 8px rgba(18,56,47,.06)",
  },
  toolbar: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "center",
    gap: "8px",
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: "10px 12px",
    backgroundColor: "#fafcfb",
  },
  conversationSelect: {
    minWidth: 0,
    width: "100%",
  },
  history: {
    display: "flex",
    overflowY: "auto",
    flexDirection: "column",
    gap: "12px",
    padding: "16px",
  },
  empty: {
    display: "grid",
    placeItems: "center",
    flexGrow: 1,
    minHeight: "240px",
    padding: "24px",
    textAlign: "center",
    color: tokens.colorNeutralForeground3,
  },
  emptyTitle: { margin: 0, color: "#17493c", fontSize: "16px", fontWeight: 650 },
  emptyText: { maxWidth: "280px", margin: "6px 0 0", fontSize: "12px", lineHeight: 1.5 },
  messageRow: { display: "flex" },
  userRow: { justifyContent: "flex-end" },
  assistantRow: { justifyContent: "flex-start" },
  message: {
    maxWidth: "82%",
    margin: 0,
    borderRadius: "12px",
    padding: "10px 12px",
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
    fontSize: "12px",
    lineHeight: 1.5,
  },
  userMessage: { color: "white", backgroundColor: "#1f5d4d", borderBottomRightRadius: "4px" },
  assistantMessage: {
    color: tokens.colorNeutralForeground1,
    backgroundColor: "#edf4f1",
    borderBottomLeftRadius: "4px",
  },
  status: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    color: tokens.colorNeutralForeground3,
    fontSize: "11px",
  },
  composer: {
    display: "grid",
    gap: "10px",
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    padding: "12px",
    backgroundColor: "#fafcfb",
  },
  rangePanel: {
    display: "grid",
    gap: "8px",
  },
  rangePanelHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: "12px",
  },
  rangePanelTitle: {
    margin: 0,
    color: tokens.colorNeutralForeground1,
    fontSize: "12px",
    fontWeight: 650,
  },
  rangePanelSummary: {
    margin: "2px 0 0",
    color: tokens.colorNeutralForeground3,
    fontSize: "10px",
  },
  rangeList: {
    display: "grid",
    maxHeight: "210px",
    overflowY: "auto",
    gap: "6px",
  },
  rangeCard: {
    border: `1px solid ${tokens.colorNeutralStroke2}`,
    borderRadius: "8px",
    backgroundColor: "white",
  },
  rangeCardHeader: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "start",
    gap: "4px",
    padding: "6px 6px 6px 8px",
  },
  rangeDetails: {
    minWidth: 0,
  },
  rangeSummary: {
    cursor: "pointer",
    color: tokens.colorNeutralForeground2,
    fontSize: "11px",
  },
  rangeAddress: {
    marginLeft: "4px",
    fontWeight: 650,
  },
  rangeDimensions: {
    marginLeft: "6px",
    color: tokens.colorNeutralForeground3,
    fontSize: "10px",
  },
  rangeTableViewport: {
    maxHeight: "140px",
    marginTop: "6px",
    overflow: "auto",
  },
  rangeTable: {
    borderCollapse: "collapse",
    fontFamily: "Consolas, monospace",
    fontSize: "10px",
    whiteSpace: "nowrap",
    "& td": {
      maxWidth: "180px",
      overflow: "hidden",
      border: `1px solid ${tokens.colorNeutralStroke2}`,
      padding: "3px 5px",
      textOverflow: "ellipsis",
    },
  },
  rangeHint: {
    margin: 0,
    color: tokens.colorNeutralForeground3,
    fontSize: "10px",
    lineHeight: 1.4,
  },
  inputRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) auto",
    alignItems: "end",
    gap: "8px",
  },
  textarea: { width: "100%" },
  hint: { margin: 0, color: tokens.colorNeutralForeground3, fontSize: "10px" },
});
